'use client'

import React from 'react'
import { store } from '../stores/store'
import { Provider } from 'react-redux'
import '../css/main.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Provider store={store}>
      <html lang="en" className="style-basic">
        {/* <head> */}
        {/* <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" /> */}
        {/* <link rel="apple-touch-icon" sizes="180x180" href="/assets/img/logo/apple-touch-icon.png" />
            <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/logo/favicon-32x32.png" />
            <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/logo/favicon-16x16.png" />
            <link rel="icon" type="image/png" href="/assets/img/logo/favicon.png" />
            <link rel="icon" href="/assets/img/logo/favicon.ico" />
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet"></link> */}
        {/* </head> */}

        <body>{children}</body>
      </html>
    </Provider>
  )
}
